### ISSUE TITLE
Undefined step: Given  I have a HomeActivity

### ISSUE THREAD

**Issue by satyaattili** [emmasuzuki/CucumberEspressoDemo#2]
Getting this exception while integrating BDD cucumber tests to my existing espresso tests.
Followed exactly the same instructions given.

Please let me know the what may be the cause. Thanks in advance.

**Comment by emmasuzuki** [comment]
Could you post your feature file and step definition file?

**Comment by satyaattili** [comment]
@emmasuzuki , Even i tried with sample project provided in git repository, I am getting same issue. 
<img width="512" alt="image" src="https://user-images.githubusercontent.com/2771854/37272185-e7e78450-25fb-11e8-8a58-c2dafa466044.png">

**Comment by emmasuzuki** [comment]
This time you cloned my project and did not change any code?  Were you able to successfully sync the project?

**Comment by emmasuzuki** [comment]
hmm. I might need to add tag and glue. 

Could you try the following? 

Add this annotation to Instrumentation.java class
```
@CucumberOptions(features = "features",
        glue = {"com.emmasuzuki.cucumberespressodemo.test"},
        tags = {"@login-feature"})
```

and remove `@CucumberOptions` annotation from the `LoginActivitySteps.java`

Then finally, add `@login-feature` at the first line of `login.feature` file.

ref: https://github.com/sebaslogen/CleanGUITestArchitecture/issues/17

**Comment by satya-hike** [comment]
@emmasuzuki , Thanks for your response. It  works for me by using tag based approach.

**Comment by emmasuzuki** [comment]
Great!  Thank you for letting me know. I will update my code.
