### ISSUE TITLE
Is it possible to use this framework on a already build application 

### ISSUE THREAD

**Issue by ibrahimazzam** [emmasuzuki/CucumberEspressoDemo#3]
Hi,

I am trying to use this automation framework, but the problem I have is that I only want to use an already built application, so that I can install this apk and run the tests on it (so no need for the app folder). Is that possible ?
Thanks in advance,

Ibrahim

**Comment by emmasuzuki** [comment]
In you case, you can follow [Setup](https://github.com/emmasuzuki/CucumberEspressoDemo#setup) and add Cucumber/Espresso on your project. Then follow the below instruction to add tests for your project.
