### ISSUE TITLE
How can we take a screenshot and include it in the report ? 

### ISSUE THREAD

**Issue by ibrahimazzam** [emmasuzuki/CucumberEspressoDemo#6]
Hello,

I have a question about how to take a screenshot that we could see in the html report ?

Thanks in advance,
Ibrahim

**Comment by emmasuzuki** [comment]
Spoon library is often used for screenshots in report. https://github.com/square/spoon
However, you have to add a little work around to make spoon work with Cucumber.

I haven't tried myself but you can check out this project.
https://github.com/sebaslogen/espresso-cucumber/blob/master/espresso-test-lib/EspressoInstrumentation/src/com/tomtom/espresso/test/actions/SpoonScreenshotAction.java
