### ISSUE TITLE
Cucumber reports for Espresso with Kotlin

### ISSUE THREAD

**Issue by rajchinta** [emmasuzuki/CucumberEspressoDemo#8]
Hi, 

I'm using Expresso With Kotlin (Followed your steps) and my tests are running fine. Although I'm seeing "No tests were found" and "Empty Test suite" message under Android studio Espresso run console. I also had cucumber for Kotlin plugin as my one of the plugin for Android studio. 

Im using following dependencies

androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
androidTestImplementation 'com.android.support.test:testing-support-lib:0.1'
androidTestImplementation 'com.android.support:support-annotations:27.0.2'
androidTestImplementation 'info.cukes:cucumber-android:1.2.4'
androidTestImplementation 'info.cukes:cucumber-picocontainer:1.2.4'

Can you help me how to get cucumber reports for Espresso with Kotlin ?

Thanks

**Comment by emmasuzuki** [comment]
Hi,

Sorry this issue is slipped out from my attention. Do you still have the issue?
